apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: litmus-poc
  namespace: litmus
  labels:
    subject: litmus-poc_litmus
    workflows.argoproj.io/controller-instanceid: b15ebd89-ae5a-4a4a-b4ea-b9f56547a217
spec:
  arguments:
    parameters:
      - name: adminModeNamespace
        value: litmus
  entrypoint: custom-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
    - name: custom-chaos
      steps:
        - - name: install-chaos-experiments
            template: install-chaos-experiments
        - - name: litmus-terminate-instance
            template: aws-ssm-chaos-by-id-lu3
        - - name: revert-chaos
            template: revert-chaos
    - name: install-chaos-experiments
      inputs:
        artifacts:
          - name: aws-ssm-chaos-by-id-lu3
            path: /tmp/aws-ssm-chaos-by-id-lu3.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                description:
                  message: |
                    Execute AWS SSM Chaos on given ec2 instance IDs
                kind: ChaosExperiment
                metadata:
                  name: aws-ssm-chaos-by-id
                  labels:
                    name: aws-ssm-chaos-by-id
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: chaosexperiment
                    app.kubernetes.io/version: 2.14.0
                spec:
                  definition:
                    scope: Cluster
                    permissions:
                      - apiGroups:
                          - ""
                        resources:
                          - pods
                        verbs:
                          - create
                          - delete
                          - get
                          - list
                          - patch
                          - update
                          - deletecollection
                      - apiGroups:
                          - ""
                        resources:
                          - events
                        verbs:
                          - create
                          - get
                          - list
                          - patch
                          - update
                      - apiGroups:
                          - ""
                        resources:
                          - secrets
                          - configmaps
                        verbs:
                          - get
                          - list
                      - apiGroups:
                          - ""
                        resources:
                          - pods/log
                        verbs:
                          - get
                          - list
                          - watch
                      - apiGroups:
                          - ""
                        resources:
                          - pods/exec
                        verbs:
                          - get
                          - list
                          - create
                      - apiGroups:
                          - batch
                        resources:
                          - jobs
                        verbs:
                          - create
                          - list
                          - get
                          - delete
                          - deletecollection
                      - apiGroups:
                          - litmuschaos.io
                        resources:
                          - chaosengines
                          - chaosexperiments
                          - chaosresults
                        verbs:
                          - create
                          - list
                          - get
                          - patch
                          - update
                          - delete
                    image: incrediblehulk/go-runner:ci
                    imagePullPolicy: Always
                    args:
                      - -c
                      - ./experiments -name aws-ssm-chaos-by-id
                    command:
                      - /bin/bash
                    env:
                      - name: TOTAL_CHAOS_DURATION
                        value: "60"
                      - name: CHAOS_INTERVAL
                        value: "60"
                      - name: RAMP_TIME
                        value: ""
                      - name: EC2_INSTANCE_ID
                        value: ""
                      - name: REGION
                        value: ""
                      - name: SEQUENCE
                        value: parallel
                      - name: DOCUMENT_NAME
                        value: ""
                      - name: DOCUMENT_TYPE
                        value: ""
                      - name: DOCUMENT_FORMAT
                        value: ""
                      - name: DOCUMENT_PATH
                        value: ""
                      - name: INSTALL_DEPENDENCIES
                        value: "True"
                      - name: NUMBER_OF_WORKERS
                        value: "1"
                      - name: MEMORY_PERCENTAGE
                        value: "80"
                      - name: CPU_CORE
                        value: "0"
                      - name: LIB
                        value: litmus
                    labels:
                      name: aws-ssm-chaos-by-id
                      app.kubernetes.io/part-of: litmus
                      app.kubernetes.io/component: experiment-job
                      app.kubernetes.io/version: 2.14.0
                    configMaps:
                      - name: litmus-terminate-instance
                        mountPath: "/mnt/litmus-terminate-instance/"
      container:
        args:
          - kubectl apply -f /tmp/aws-ssm-chaos-by-id-lu3.yaml -n
            {{workflow.parameters.adminModeNamespace}} &&  sleep 30
        command:
          - sh
          - -c
        image: litmuschaos/k8s:2.14.0
    - name: aws-ssm-chaos-by-id-lu3
      inputs:
        artifacts:
          - name: aws-ssm-chaos-by-id-lu3
            path: /tmp/chaosengine-aws-ssm-chaos-by-id-lu3.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                kind: ChaosEngine
                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  generateName: aws-ssm-chaos-by-id-lu3
                  labels:
                    workflow_run_id: "{{workflow.uid}}"
                spec:
                  engineState: active
                  chaosServiceAccount: litmus-admin
                  components:
                    runner:
                  experiments:
                    - name: aws-ssm-chaos-by-id
                      spec:
                        components:
                          env:
                            - name: TOTAL_CHAOS_DURATION
                              value: "360"
                            - name: CHAOS_INTERVAL
                              value: "120"
                            - name: EC2_INSTANCE_ID
                              value: i-0da74bcaa6357ad60
                            - name: REGION
                              value: "us-east-1"
                            - name: MEMORY_PERCENTAGE
                              value: "80"
                            - name: CPU_CORE
                              value: "0"
                            - name: DOCUMENT_NAME
                              value: "litmus-terminate-instance"
                            - name: DOCUMENT_TYPE
                              value: ""
                            - name: DOCUMENT_FORMAT
                              value: ""
                            - name: DOCUMENT_PATH
                              value: "/mnt/litmus-terminate-instance/litmus-terminate-instance.yaml"
                            - name: INSTALL_DEPENDENCIES
                              value: "True"
                        probe: []
      container:
        args:
          - -file=/tmp/chaosengine-aws-ssm-chaos-by-id-lu3.yaml
          - -saveName=/tmp/engine-name
        image: litmuschaos/litmus-checker:2.14.0
    - name: revert-chaos
      container:
        image: litmuschaos/k8s:2.14.0
        command:
          - sh
          - -c
        args:
          - kubectl delete chaosengine -l workflow_run_id={{workflow.uid}} -n
            {{workflow.parameters.adminModeNamespace}}
  podGC:
    strategy: OnWorkflowCompletion
